<?xml version="1.0" encoding="ASCII"?>

<!-- oks-schema version 2.0 -->


<!DOCTYPE oks-schema [
  <!ELEMENT oks-schema (info, (include)?, (comments)?, (class)+)>
  <!ELEMENT info EMPTY>
  <!ATTLIST info
      name CDATA #REQUIRED
      type CDATA #REQUIRED
      num-of-includes CDATA #REQUIRED
      num-of-items CDATA #REQUIRED
      oks-format CDATA #FIXED "schema"
      oks-version CDATA #REQUIRED
      created-by CDATA #REQUIRED
      created-on CDATA #REQUIRED
      creation-time CDATA #REQUIRED
      last-modified-by CDATA #REQUIRED
      last-modified-on CDATA #REQUIRED
      last-modification-time CDATA #REQUIRED
  >
  <!ELEMENT include (file)+>
  <!ELEMENT file EMPTY>
  <!ATTLIST file
      path CDATA #REQUIRED
  >
  <!ELEMENT comments (comment)+>
  <!ELEMENT comment EMPTY>
  <!ATTLIST comment
      creation-time CDATA #REQUIRED
      created-by CDATA #REQUIRED
      created-on CDATA #REQUIRED
      author CDATA #REQUIRED
      text CDATA #REQUIRED
  >
  <!ELEMENT class (superclass | attribute | relationship | method)*>
  <!ATTLIST class
      name CDATA #REQUIRED
      description CDATA ""
      is-abstract (yes|no) "no"
  >
  <!ELEMENT superclass EMPTY>
  <!ATTLIST superclass name CDATA #REQUIRED>
  <!ELEMENT attribute EMPTY>
  <!ATTLIST attribute
      name CDATA #REQUIRED
      description CDATA ""
      type (bool|s8|u8|s16|u16|s32|u32|s64|u64|float|double|date|time|string|uid|enum|class) #REQUIRED
      range CDATA ""
      format (dec|hex|oct) "dec"
      is-multi-value (yes|no) "no"
      multi-value-implementation (list|vector) "list"
      init-value CDATA ""
      is-not-null (yes|no) "no"
  >
  <!ELEMENT relationship EMPTY>
  <!ATTLIST relationship
      name CDATA #REQUIRED
      description CDATA ""
      class-type CDATA #REQUIRED
      low-cc (zero|one) #REQUIRED
      high-cc (one|many) #REQUIRED
      is-composite (yes|no) #REQUIRED
      is-exclusive (yes|no) #REQUIRED
      is-dependent (yes|no) #REQUIRED
      multi-value-implementation (list|vector) "list"
  >
  <!ELEMENT method (method-implementation*)>
  <!ATTLIST method
      name CDATA #REQUIRED
      description CDATA ""
  >
  <!ELEMENT method-implementation EMPTY>
  <!ATTLIST method-implementation
      language CDATA #REQUIRED
      prototype CDATA #REQUIRED
      body CDATA ""
  >
]>

<oks-schema>

<info name="" type="" num-of-includes="1" num-of-items="3" oks-format="schema" oks-version="oks-03-10-01 built &quot;Mar 12 2008&quot;" created-by="rabello" created-on="pcuwtr1.cern.ch" creation-time="10/5/07 10:07:03" last-modified-by="wiedenat" last-modified-on="pcuw18.cern.ch" last-modification-time="26/3/08 18:51:46"/>

<include>
 <file path="daq/schema/df.schema.xml"/>
</include>


 <class name="HLTCommonParameters" description="Common configuration parameters for bootstraping the HLT framework used by HLT trigger implementation classes">
  <attribute name="messageSvcType" description="The implementation of the message service to use." type="string" init-value="TrigMessageSvc" is-not-null="yes"/>
  <attribute name="jobOptionsSvcType" description="Implementation of the jobOptions service to use." type="string" init-value="JobOptionsSvc" is-not-null="yes"/>
  <attribute name="dllName" description="The name of the library containing the Gaudi bootstrap code" type="string"/>
  <attribute name="factoryName" description="Name of the factory function inside dllName that can bootstrap Gaudi." type="string"/>
 </class>

 <class name="HLTImplementationDB" description="OKS type for HLT running through a database connection">
  <superclass name="HLTImplementation"/>
  <attribute name="instance" description="The set of chains to use for HLT (L2 or EF)." type="enum" range="L2,EF"/>
  <attribute name="hltPrescaleKey" description="Configuration key for HLT prescale set" type="string"/>
  <attribute name="configureHLTMenuFrom" description="Configuration source for HLT menu" type="enum" range="DB,XML" init-value="DB"/>
  <attribute name="additionalConnectionParameters" description="additional connection string parameters" type="string" is-multi-value="yes"/>
  <relationship name="HLTCommonParameters" description="Relationshipt to common HLT configuration parameters." class-type="HLTCommonParameters" low-cc="zero" high-cc="one" is-composite="no" is-exclusive="no" is-dependent="no"/>
  <relationship name="TriggerDBConnection" description="Relationship to database connection parameters
" class-type="TriggerDBConnection" low-cc="zero" high-cc="one" is-composite="no" is-exclusive="no" is-dependent="no"/>
 </class>

 <class name="HLTImplementationDBPython" description="OKS type for HLT running through a database connection including Python pre/postCommand. This is for debugging purposes only and should not be used for online running.">
  <superclass name="HLTImplementationDB"/>
  <attribute name="preCommand" description="A set of python commands or script to be executed before DB configuration." type="string" is-multi-value="yes"/>
  <attribute name="postCommand" description="A set of python commands or script to be executed after DB configuration." type="string" is-multi-value="yes"/>
 </class>
    
 <class name="HLTImplementationJobOptions" description="OKS type for python JobOption HLT running.">
  <superclass name="HLTImplementation"/>
  <attribute name="jobOptionsPath" description="Path (full or relative) to the top-level jobotions you want run with." type="string" is-not-null="yes"/>
  <attribute name="evtSel" description="The event selector" type="string" init-value="NONE" is-not-null="yes"/>
  <attribute name="pythonSetupFile" description="The bootstrapping python file for the PSC" type="string"/>
  <attribute name="showInclude" description="If we should show the files we include() as we go." type="bool" init-value="0"/>
  <attribute name="logLevel" description="The logging level to be set at the MessageService" type="string" is-multi-value="yes" init-value="ERROR"/>
  <attribute name="tracePattern" description="If we should trace some particular include()&apos;s" type="string"/>
  <attribute name="preCommand" description="A set of python commands to be executed just before the execution of your top-level jobOptions." type="string" is-multi-value="yes"/>
  <attribute name="postCommand" description="A set of python commands to be executed just after reading your top-level python joboptions, near the end of the configuration phase" type="string" is-multi-value="yes"/>
  <relationship name="HLTCommonParameters" description="Common parameters that dictate common behavior between python jobOptions and DB implementations of the PSC configuration" class-type="HLTCommonParameters" low-cc="zero" high-cc="one" is-composite="no" is-exclusive="no" is-dependent="no"/>
 </class>

</oks-schema>
