<?xml version="1.0" encoding="ASCII"?>

<!-- oks-schema version 2.0 -->


<!DOCTYPE oks-schema [
  <!ELEMENT oks-schema (info, (include)?, (class)+)>
  <!ELEMENT info EMPTY>
  <!ATTLIST info
      name CDATA #REQUIRED
      type CDATA #REQUIRED
      num-of-includes CDATA #REQUIRED
      num-of-items CDATA #REQUIRED
      oks-format CDATA #FIXED "schema"
      oks-version CDATA #REQUIRED
      created-by CDATA #REQUIRED
      created-on CDATA #REQUIRED
      creation-time CDATA #REQUIRED
      last-modified-by CDATA #REQUIRED
      last-modified-on CDATA #REQUIRED
      last-modification-time CDATA #REQUIRED
  >
  <!ELEMENT include (file)+>
  <!ELEMENT file EMPTY>
  <!ATTLIST file
      path CDATA #REQUIRED
  >
  <!ELEMENT class (superclass | attribute | relationship | method)*>
  <!ATTLIST class
      name CDATA #REQUIRED
      description CDATA ""
      is-abstract (yes|no) "no"
  >
  <!ELEMENT superclass EMPTY>
  <!ATTLIST superclass name CDATA #REQUIRED>
  <!ELEMENT attribute EMPTY>
  <!ATTLIST attribute
      name CDATA #REQUIRED
      description CDATA ""
      type (bool|s8|u8|s16|u16|s32|u32|float|double|date|time|string|uid|enum) #REQUIRED
      range CDATA ""
      format (dec|hex|oct) "dec"
      is-multi-value (yes|no) "no"
      multi-value-implementation (list|vector) "list"
      init-value CDATA ""
      is-not-null (yes|no) "no"
  >
  <!ELEMENT relationship EMPTY>
  <!ATTLIST relationship
      name CDATA #REQUIRED
      description CDATA ""
      class-type CDATA #REQUIRED
      low-cc (zero|one) #REQUIRED
      high-cc (one|many) #REQUIRED
      is-composite (yes|no) #REQUIRED
      is-exclusive (yes|no) #REQUIRED
      is-dependent (yes|no) #REQUIRED
      multi-value-implementation (list|vector) "list"
  >
  <!ELEMENT method (method-implementation*)>
  <!ATTLIST method
      name CDATA #REQUIRED
      description CDATA ""
  >
  <!ELEMENT method-implementation EMPTY>
  <!ATTLIST method-implementation
      language CDATA #REQUIRED
      prototype CDATA #REQUIRED
      body CDATA ""
  >
]>

<oks-schema>

  <info name="" type="" num-of-includes="1" num-of-items="2" oks-format="schema" oks-version="oks-03-07-02 built &quot;Jul 23 2007&quot;" created-by="pauly" created-on="pcphate12.cern.ch" creation-time="20/7/06 15:42:51" last-modified-by="pauly" last-modified-on="pcphate14" last-modification-time="20/8/07 14:44:05"/>
  
  <include>
    <file path="is/is.xml"/>
  </include>
  
  <class name="TrigConfL1PsKey" description="Current L1 prescale key">
    <superclass name="Info"/>
    <attribute name="L1PrescaleKey" description="L1 prescale key of the trigger configuration" type="u32"/>
    <attribute name="L1PrescaleComment" description="L1 prescale comment" type="string"/>
  </class>
  
  <class name="TrigConfL1BgKey" description="Current L1 bunch group key">
    <superclass name="Info"/>
    <attribute name="L1BunchGroupKey" description="LVL1 bunch group key of the trigger configuration" type="u32"/>
    <attribute name="L1BunchGroupComment" description="LVL1 bunch group comment" type="string"/>
  </class>
  
  <class name="TrigConfRelease" description="HLT Release description">
    <superclass name="Info"/>
    <attribute name="HLTReleaseVersion" description="Release and patch version like 15.5.1.2" type="string"/>
    <attribute name="HLTPatchProject" description="Name of patch project, usualy AtlasP1HLT" type="string"/>
    <attribute name="HLTExtraPatch" description="Path to extra patch area, should be empty except during commissioning" type="string"/>
  </class>
  
</oks-schema>
