<?xml version="1.0" encoding="ASCII"?>

<!-- oks-data version 2.0 -->


<!DOCTYPE oks-data [
  <!ELEMENT oks-data (info, (include)?, (obj)+)>
  <!ELEMENT info EMPTY>
  <!ATTLIST info
      name CDATA #REQUIRED
      type CDATA #REQUIRED
      num-of-includes CDATA #REQUIRED
      num-of-items CDATA #REQUIRED
      oks-format CDATA #FIXED "extended"
      oks-version CDATA #REQUIRED
      created-by CDATA #REQUIRED
      created-on CDATA #REQUIRED
      creation-time CDATA #REQUIRED
      last-modified-by CDATA #REQUIRED
      last-modified-on CDATA #REQUIRED
      last-modification-time CDATA #REQUIRED
  >
  <!ELEMENT include (file)+>
  <!ELEMENT file EMPTY>
  <!ATTLIST file
      path CDATA #REQUIRED
  >
  <!ELEMENT obj (attr | rel)*>
  <!ATTLIST obj
      class CDATA #REQUIRED
      id CDATA #REQUIRED
  >
  <!ELEMENT attr (#PCDATA)*>
  <!ATTLIST attr
      name CDATA #REQUIRED
      type (bool|s8|u8|s16|u16|s32|u32|s64|u64|float|double|date|time|string|uid|enum|class|-) "-"
      num CDATA "-1"
  >
  <!ELEMENT rel (#PCDATA)*>
  <!ATTLIST rel
      name CDATA #REQUIRED
      num CDATA "-1"
  >
]>

<oks-data>

<info name="" type="" num-of-includes="1" num-of-items="103" oks-format="extended" oks-version="oks-03-08-00 built &quot;Oct  4 2007&quot;" created-by="rabello" created-on="pcuwtr1.cern.ch" creation-time="5/10/07 17:31:56" last-modified-by="rabello" last-modified-on="pcuwtr1.cern.ch" last-modification-time="5/10/07 17:31:56"/>

<include>
 <file path="daq/schema/core.schema.xml"/>
</include>


<obj class="Computer" id="pcatb120.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"4 core(s) of Intel(R) XEON(TM) CPU 2.20GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">513</attr>
 <attr name="CPU" type="u16">2197</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb120.cern.ch-eth0"
  "NetworkInterface" "pcatb120.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb122.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) XEON(TM) CPU 2.20GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">2197</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb122.cern.ch-eth0"
  "NetworkInterface" "pcatb122.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb123.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) XEON(TM) CPU 2.20GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">2196</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb123.cern.ch-eth0"
  "NetworkInterface" "pcatb123.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb124.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) XEON(TM) CPU 2.20GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">2197</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb124.cern.ch-eth0"
  "NetworkInterface" "pcatb124.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb125.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) XEON(TM) CPU 2.20GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">2196</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb125.cern.ch-eth0"
  "NetworkInterface" "pcatb125.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb126.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) XEON(TM) CPU 2.20GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">2196</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb126.cern.ch-eth0"
  "NetworkInterface" "pcatb126.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb127.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) XEON(TM) CPU 2.20GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">2197</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb127.cern.ch-eth0"
  "NetworkInterface" "pcatb127.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb129.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) XEON(TM) CPU 2.40GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">2396</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb129.cern.ch-eth0"
  "NetworkInterface" "pcatb129.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb131.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) XEON(TM) CPU 2.40GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">2396</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb131.cern.ch-eth0"
  "NetworkInterface" "pcatb131.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb132.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) XEON(TM) CPU 2.40GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">2396</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb132.cern.ch-eth0"
  "NetworkInterface" "pcatb132.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb133.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) XEON(TM) CPU 2.20GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">2197</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb133.cern.ch-eth0"
  "NetworkInterface" "pcatb133.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb134.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) XEON(TM) CPU 2.20GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">2197</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb134.cern.ch-eth0"
  "NetworkInterface" "pcatb134.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb135.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"4 core(s) of Intel(R) XEON(TM) CPU 2.20GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1033</attr>
 <attr name="CPU" type="u16">2197</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb135.cern.ch-eth0"
  "NetworkInterface" "pcatb135.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb136.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) XEON(TM) CPU 2.20GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">2197</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb136.cern.ch-eth0"
  "NetworkInterface" "pcatb136.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb137.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) XEON(TM) CPU 2.20GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">2197</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb137.cern.ch-eth0"
  "NetworkInterface" "pcatb137.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb138.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) XEON(TM) CPU 2.40GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">2396</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb138.cern.ch-eth0"
  "NetworkInterface" "pcatb138.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb139.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) XEON(TM) CPU 2.40GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">2396</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb139.cern.ch-eth0"
  "NetworkInterface" "pcatb139.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb140.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) Xeon(TM) CPU 3.06GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">3066</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="1">
  "NetworkInterface" "pcatb140.cern.ch-eth0"
 </rel>
</obj>

<obj class="Computer" id="pcatb141.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) Xeon(TM) CPU 3.06GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">3066</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb141.cern.ch-eth0"
  "NetworkInterface" "pcatb141.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb142.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) Xeon(TM) CPU 3.06GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">3066</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb142.cern.ch-eth0"
  "NetworkInterface" "pcatb142.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb143.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) Xeon(TM) CPU 3.06GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">3066</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb143.cern.ch-eth0"
  "NetworkInterface" "pcatb143.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb144.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) Xeon(TM) CPU 3.06GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">3066</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb144.cern.ch-eth0"
  "NetworkInterface" "pcatb144.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb145.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) Xeon(TM) CPU 3.06GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">3066</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb145.cern.ch-eth0"
  "NetworkInterface" "pcatb145.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb146.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) Xeon(TM) CPU 3.06GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">3066</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb146.cern.ch-eth0"
  "NetworkInterface" "pcatb146.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb147.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) Xeon(TM) CPU 3.06GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">3066</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb147.cern.ch-eth0"
  "NetworkInterface" "pcatb147.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb148.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) Xeon(TM) CPU 3.06GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">3066</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb148.cern.ch-eth0"
  "NetworkInterface" "pcatb148.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatb149.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) Xeon(TM) CPU 3.06GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">3066</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatb149.cern.ch-eth0"
  "NetworkInterface" "pcatb149.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatr08.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) Xeon(TM) CPU 2.40GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1034</attr>
 <attr name="CPU" type="u16">2392</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="1">
  "NetworkInterface" "pcatr08.cern.ch-eth0"
 </rel>
</obj>

<obj class="Computer" id="pcatr11.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc3"</attr>
 <attr name="Type" type="string">"4 core(s) of Dual Core AMD Opteron(tm) Processor 265"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">2022</attr>
 <attr name="CPU" type="u16">1804</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="1">
  "NetworkInterface" "pcatr11.cern.ch-eth0"
 </rel>
</obj>

<obj class="Computer" id="pcatr14.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"4 core(s) of Intel(R) Xeon(R) CPU            5160  @ 3.00GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">8162</attr>
 <attr name="CPU" type="u16">3000</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatr14.cern.ch-eth0"
  "NetworkInterface" "pcatr14.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatr15.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"8 core(s) of Intel(R) Xeon(R) CPU           E5345  @ 2.33GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">12302</attr>
 <attr name="CPU" type="u16">2333</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="1">
  "NetworkInterface" "pcatr15.cern.ch-eth0"
 </rel>
</obj>

<obj class="Computer" id="pcatr16.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"4 core(s) of Intel(R) Xeon(R) CPU            5160  @ 3.00GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">8150</attr>
 <attr name="CPU" type="u16">2992</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatr16.cern.ch-eth0"
  "NetworkInterface" "pcatr16.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatr17.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"4 core(s) of Intel(R) Xeon(R) CPU            5160  @ 3.00GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">8150</attr>
 <attr name="CPU" type="u16">2992</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="2">
  "NetworkInterface" "pcatr17.cern.ch-eth0"
  "NetworkInterface" "pcatr17.cern.ch-eth1"
 </rel>
</obj>

<obj class="Computer" id="pcatr18a.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"1 core(s) of Intel(R) Xeon(R) CPU            5160  @ 3.00GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1035</attr>
 <attr name="CPU" type="u16">2992</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="1">
  "NetworkInterface" "pcatr18a.cern.ch-eth0"
 </rel>
</obj>

<obj class="Computer" id="pcatr18b.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"1 core(s) of Intel(R) Xeon(R) CPU            5160  @ 3.00GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">1025</attr>
 <attr name="CPU" type="u16">2992</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="1">
  "NetworkInterface" "pcatr18b.cern.ch-eth0"
 </rel>
</obj>

<obj class="Computer" id="pcatr18c.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) Xeon(R) CPU            5160  @ 3.00GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">2074</attr>
 <attr name="CPU" type="u16">2993</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="1">
  "NetworkInterface" "pcatr18c.cern.ch-eth0"
 </rel>
</obj>

<obj class="Computer" id="pcatr18d.cern.ch">
 <attr name="HW_Tag" type="enum">"i686-slc4"</attr>
 <attr name="Type" type="string">"2 core(s) of Intel(R) Xeon(R) CPU            5160  @ 3.00GHz"</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="Memory" type="u16">2056</attr>
 <attr name="CPU" type="u16">2992</attr>
 <attr name="RLogin" type="string">"ssh"</attr>
 <rel name="Interfaces" num="1">
  "NetworkInterface" "pcatr18d.cern.ch-eth0"
 </rel>
</obj>

<obj class="NetworkInterface" id="pcatb120.cern.ch-eth0">
 <attr name="Type" type="string">""</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="IPAddress" type="string">"137.138.227.120"</attr>
 <attr name="MACAddress" type="string">"00:30:48:12:33:97"</attr>
 <attr name="Label" type="enum">"NONE"</attr>
 <attr name="InterfaceName" type="string">"eth0"</attr>
</obj>

<obj class="NetworkInterface" id="pcatb120.cern.ch-eth1">
 <attr name="Type" type="string">""</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="IPAddress" type="string">"192.168.100.120"</attr>
 <attr name="MACAddress" type="string">"00:30:48:12:2F:4A"</attr>
 <attr name="Label" type="enum">"NONE"</attr>
 <attr name="InterfaceName" type="string">"eth1"</attr>
</obj>

<obj class="NetworkInterface" id="pcatb122.cern.ch-eth0">
 <attr name="Type" type="string">""</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="IPAddress" type="string">"137.138.227.122"</attr>
 <attr name="MACAddress" type="string">"00:30:48:23:BE:1E"</attr>
 <attr name="Label" type="enum">"NONE"</attr>
 <attr name="InterfaceName" type="string">"eth0"</attr>
</obj>

<obj class="NetworkInterface" id="pcatb122.cern.ch-eth1">
 <attr name="Type" type="string">""</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="IPAddress" type="string">"192.168.100.122"</attr>
 <attr name="MACAddress" type="string">"00:30:48:23:BE:1D"</attr>
 <attr name="Label" type="enum">"NONE"</attr>
 <attr name="InterfaceName" type="string">"eth1"</attr>
</obj>

<obj class="NetworkInterface" id="pcatb123.cern.ch-eth0">
 <attr name="Type" type="string">""</attr>
 <attr name="Location" type="string">""</attr>
 <attr name="Description" type="string">""</attr>
 <attr name="HelpLink" type="string">""</attr>
 <attr name="InstallationRef" type="string">""</attr>
 <attr name="State" type="bool">1</attr>
 <attr name="IPAddress" type="string">"137.138.227.123"</attr>
 <attr name="MACAddress" type="string">"00:30:48:23:BB:D2"</attr>
 <attr name="Label" type="enum">"NONE"</attr>
 <attr name="InterfaceName" type="string">"eth0"</attr>
</obj>

<obj class="NetworkInterface" id="pcatb123.cern.ch-eth1">
 <attr name="Type" type="string">""</attr>
 <attr name="Location" type="string">""</attr>