<?xml version="1.0" encoding="ASCII"?>

<!-- oks-data version 2.0 -->


<!DOCTYPE oks-data [
  <!ELEMENT oks-data (info, (include)?, (comments)?, (obj)+)>
  <!ELEMENT info EMPTY>
  <!ATTLIST info
      name CDATA #REQUIRED
      type CDATA #REQUIRED
      num-of-includes CDATA #REQUIRED
      num-of-items CDATA #REQUIRED
      oks-format CDATA #FIXED "extended"
      oks-version CDATA #REQUIRED
      created-by CDATA #REQUIRED
      created-on CDATA #REQUIRED
      creation-time CDATA #REQUIRED
      last-modified-by CDATA #REQUIRED
      last-modified-on CDATA #REQUIRED
      last-modification-time CDATA #REQUIRED
  >
  <!ELEMENT include (file)+>
  <!ELEMENT file EMPTY>
  <!ATTLIST file
      path CDATA #REQUIRED
  >
  <!ELEMENT comments (comment)+>
  <!ELEMENT comment EMPTY>
  <!ATTLIST comment
      creation-time CDATA #REQUIRED
      created-by CDATA #REQUIRED
      created-on CDATA #REQUIRED
      author CDATA #REQUIRED
      text CDATA #REQUIRED
  >
  <!ELEMENT obj (attr | rel)*>
  <!ATTLIST obj
      class CDATA #REQUIRED
      id CDATA #REQUIRED
  >
  <!ELEMENT attr (#PCDATA)*>
  <!ATTLIST attr
      name CDATA #REQUIRED
      type (bool|s8|u8|s16|u16|s32|u32|s64|u64|float|double|date|time|string|uid|enum|class|-) "-"
      num CDATA "-1"
  >
  <!ELEMENT rel (#PCDATA)*>
  <!ATTLIST rel
      name CDATA #REQUIRED
      num CDATA "-1"
  >
]>

<oks-data>

<info name="" type="" num-of-includes="5" num-of-items="8" oks-format="extended" oks-version="oks-03-12-00 built &quot;Jun 18 2008&quot;" created-by="rabello" created-on="pc-tdq-onl-22.cern.ch" creation-time="6/5/08 15:36:22" last-modified-by="glehmann" last-modified-on="pc-tdq-onl-25.cern.ch" last-modification-time="11/7/08 10:07:37"/>

<include>
 <file path="daq/sw/common-templates.data.xml"/>
 <file path="daq/sw/HLT_SW_Repository.data.xml"/>
 <file path="daq/sw/CoralServer-repository.data.xml"/>
</include>

<comments>
</comments>

<obj class="InfrastructureTemplateApplication" id="TopCoralProxy">
 <attr name="Parameters" type="string">"-m -p 3320 -s 40007 env:TDAQ_CORAL_PROXY_PARENT"</attr>
 <attr name="RestartParameters" type="string">"-m -p 3320 -s 40007 env:TDAQ_CORAL_PROXY_PARENT"</attr>
 <attr name="Logging" type="bool">1</attr>
 <attr name="InputDevice" type="string">""</attr>
 <attr name="InitTimeout" type="u32">0</attr>
 <attr name="StartIn" type="string">""</attr>
 <attr name="StartAt" type="enum">"Boot"</attr>
 <attr name="StopAt" type="enum">"Shutdown"</attr>
 <attr name="RestartableDuringRun" type="bool">1</attr>
 <attr name="IfDies" type="enum">"Error"</attr>
 <attr name="IfFailed" type="enum">"Error"</attr>
 <attr name="Instances" type="u16">1</attr>
 <attr name="SegmentProcEnvVarName" type="string">"TDAQ_CORAL_PROXY_HOST"</attr>
 <attr name="SegmentProcEnvVarParentName" type="string">"TDAQ_CORAL_PROXY_PARENT"</attr>
 <attr name="SegmentProcEnvVarValue" type="enum">"runsOn"</attr>
 <rel name="InitializationDependsFrom" num="0"></rel>
 <rel name="ShutdownDependsFrom" num="0"></rel>
 <rel name="Program">"Binary" "coralServerProxy"</rel>
 <rel name="ExplicitTag">"" ""</rel>
 <rel name="Uses" num="0"></rel>
 <rel name="ProcessEnvironment" num="0"></rel>
 <rel name="BackupHosts" num="0"></rel>
</obj>

<obj class="InfrastructureTemplateApplication" id="RackCoralProxy">
 <attr name="Parameters" type="string">"-v -m -p 3320 -s 3320 env:TDAQ_CORAL_PROXY_PARENT"</attr>
 <attr name="RestartParameters" type="string">"-v -m -p 3320 -s 3320 env:TDAQ_CORAL_PROXY_PARENT"</attr>
 <attr name="Logging" type="bool">1</attr>
 <attr name="InputDevice" type="string">""</attr>
 <attr name="InitTimeout" type="u32">0</attr>
 <attr name="StartIn" type="string">""</attr>
 <attr name="StartAt" type="enum">"Boot"</attr>
 <attr name="StopAt" type="enum">"Shutdown"</attr>
 <attr name="RestartableDuringRun" type="bool">1</attr>
 <attr name="IfDies" type="enum">"Restart"</attr>
 <attr name="IfFailed" type="enum">"Error"</attr>
 <attr name="Instances" type="u16">1</attr>
 <attr name="SegmentProcEnvVarName" type="string">"TDAQ_CORAL_PROXY_HOST"</attr>
 <attr name="SegmentProcEnvVarParentName" type="string">"TDAQ_CORAL_PROXY_PARENT"</attr>
 <attr name="SegmentProcEnvVarValue" type="enum">"runsOn"</attr>
 <rel name="InitializationDependsFrom" num="0"></rel>
 <rel name="ShutdownDependsFrom" num="0"></rel>
 <rel name="Program">"Binary" "coralServerProxy"</rel>
 <rel name="ExplicitTag">"" ""</rel>
 <rel name="Uses" num="0"></rel>
 <rel name="ProcessEnvironment" num="0"></rel>
 <rel name="BackupHosts" num="0"></rel>
</obj>


<obj class="TemplateApplication" id="NodeCoralProxy">
 <attr name="Parameters" type="string">"-m -p 3320 -s 3320 env:TDAQ_CORAL_PROXY_HOST"</attr>
 <attr name="RestartParameters" type="string">"-m -p 3320 -s 3320 env:TDAQ_CORAL_PROXY_HOST"</attr>
 <attr name="Logging" type="bool">1</attr>
 <attr name="InputDevice" type="string">""</attr>
 <attr name="InitTimeout" type="u32">0</attr>
 <attr name="StartIn" type="string">""</attr>
 <attr name="StartAt" type="enum">"Boot"</attr>
 <attr name="StopAt" type="enum">"Shutdown"</attr>
 <attr name="RestartableDuringRun" type="bool">1</attr>
 <attr name="IfDies" type="enum">"Restart"</attr>
 <attr name="IfFailed" type="enum">"Ignore"</attr>
 <attr name="Instances" type="u16">1</attr>
 <rel name="InitializationDependsFrom" num="0"></rel>
 <rel name="ShutdownDependsFrom" num="0"></rel>
 <rel name="Program">"Binary" "coralServerProxy"</rel>
 <rel name="ExplicitTag">"" ""</rel>
 <rel name="Uses" num="0"></rel>
 <rel name="ProcessEnvironment" num="0"></rel>
</obj>

<obj class="Variable" id="DEFAULT_HLT_CORAL_AUTH_PATH">
 <attr name="Description" type="string">""</attr>
 <attr name="Name" type="string">"CORAL_AUTH_PATH"</attr>
 <attr name="Value" type="string">"/tmp/coral-proxy/${TDAQ_PARTITION}"</attr>
 <rel name="TagValues" num="0"></rel>
</obj>

<obj class="Variable" id="DEFAULT_HLT_CORAL_DBLOOKUP_PATH">
 <attr name="Description" type="string">""</attr>
 <attr name="Name" type="string">"CORAL_DBLOOKUP_PATH"</attr>
 <attr name="Value" type="string">"/tmp/coral-proxy/${TDAQ_PARTITION}"</attr>
 <rel name="TagValues" num="0"></rel>
</obj>

<obj class="TemplateApplication" id="HLT_DB_Gen">
 <attr name="Parameters" type="string">""</attr>
 <attr name="RestartParameters" type="string">""</attr>
 <attr name="IfDies" type="enum">"Error"</attr>
 <attr name="IfFailed" type="enum">"Ignore"</attr>
 <attr name="StartAt" type="enum">"Boot"</attr>
 <attr name="StopAt" type="enum">"UserDefined"</attr>
 <attr name="InitTimeout" type="u32">60</attr>
 <attr name="StartIn" type="string">""</attr>
 <attr name="InputDevice" type="string">""</attr>
 <attr name="Logging" type="bool">1</attr>
 <attr name="Instances" type="u16">1</attr>
 <rel name="InitializationDependsFrom" num="0"></rel>
 <rel name="ShutdownDependsFrom" num="0"></rel>
 <rel name="Program">"Binary" "dal_create_db_connection_files"</rel>
 <rel name="ExplicitTag">"" ""</rel>
 <rel name="Uses" num="0"></rel>
 <rel name="ProcessEnvironment" num="2">
  "Variable" "DEFAULT_HLT_CORAL_DBLOOKUP_PATH"
  "Variable" "DEFAULT_HLT_CORAL_AUTH_PATH"
 </rel>
</obj>

</oks-data>
